import { CapitalGains } from './capital-gains'

export type Year = number

/**
 * Aggregation of the capital gains by year.
 * Maps from year to the capital gains realized in that year.
 */
export type YearlyCapitalGains = Record<Year, number>

/**
 * Aggregates the capital gains generated by a sequence of sales by year
 *
 * @param saleCapitalGains Array of capital gains generated by sell operations
 *
 * @returns A map of year to capital gains generated in the given year
 */
export function aggregateByYear(
  saleCapitalGains: CapitalGains[]
): YearlyCapitalGains {
  return saleCapitalGains.reduce<YearlyCapitalGains>(
    (capitalGainsPerYear, { capitalGains, sale: { date } }) => ({
      ...capitalGainsPerYear,
      [date.getFullYear()]:
        (capitalGainsPerYear[date.getFullYear()] || 0) + capitalGains,
    }),
    {}
  )
}
